title: 'Pragma'

nav:
  - { title: 'Home', href: '/' }

markdown: kramdown

sass:
  sass_dir: css
  style: expanded

exclude:
  - .ruby-version
  - .ruby-gemset
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - package.json
  - package-lock.json
